language: java
sudo: false
branches:
  except:
  - "/^feature.*$/"
jdk:
- oraclejdk7
env:
  global:
    - secure: Cae9tcMEiwk4yPvraZKEy5r051jDz1JmDYCIzX+h+wz3CaRJaTHf1J4K6u9Uv/H2wAe1iPnC/Z1nk4sF0wsuNrQQzP35V0i42tLlFMNoPkZOvlOKDaQHdMx/9YTf29VM83/FCmLwsxYhOqV7ZpKK03zRD8RyWEwOwZ+wXj9Rk3z1qAhRyCSKZpLtcUVp7YD5PwV0Rm2AJ2EI9OADPD8hfOClWXVpC54bWtguGxrWy2T9F83PHPMqHsIMubHLa7EtuBvVVxlCZh0wOysvYMGmONV29mAMLtyW5FLaes9C9Ab1gFZj1T1mdQRikPZ4uyVBGURo1mvbGrjirJEmsA/slQVBB8LIFDSAXrHuvpOyvqZbJfP15eImsfEX7DBL24MHnS7hETqRmbxxmVXCC4z3/9PHJhSE+IXLBTEUr4h/sAE5f/ulV/f34ivUyMBiuTkr1aQwjO+n4Miy6x2Bp8BEsfacAUXUhApboppatxIeBovJSi7EMj2h6hEOB0ORuOVB6m5OQune00/c7jE5FmSx2n0aYKs/BzHWxJY/OG6ruDKykbK1DeP/5Lv4UhvMwJjLu1Ot9vvDqae+N4fSmpVFgKqF8ifg3XrX0Ky/rEieI73/VOGY1PqBIwm7oVWdyTKqSAWmk5kthVnxxcO/OCDF4pTo4LKkj0eqr93Ht9CaH1A=

script:
  # Run tests when not on coverity branch.
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      ./gradlew check;
    fi

after_script:
- cat /home/travis/build/gatzka/java-jet/cov-int/build-log.txt

addons:
  coverity_scan:
    project:
      name: gatzka/java-jet
      description: Build submitted via Travis CI
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: coverity_scan
