language: java
sudo: false
branches:
  except:
  - "/^feature.*$/"
jdk:
- oraclejdk7
before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: gatzka/java-jet
      description: Build submitted via Travis CI
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew compileJava"
    branch_pattern: coverity_scan
env:
  global:
    - secure: q4mrIb55DtO+997cBrmosUt7idloVoYCrmzRoMjL+TY+PuqBndkuEP9cJiXCfV9btRTWgMhOBY8Ixf3VQqSIIeYScLLJ3lnLhXk5p7nBEPvyqndSGMvysxUeF3ZywHrSQnEbGZAHWQv16Ys0VSd3KbNTUt4FJiB6oR6R1u1t3deQIeDjEiVY8JQ/ypz8Ax1PKpoUsvOwFs25KSobysDWmCjGwvGzSdHV+TkLOiqjiLTkq8f9+ZLw12+TEaTcln44oXHkszQJjc4q9IzZJDAp7sRMtpWtH1Jk/THcsr+OW6e1AEzrgahsLNllltaCVejovbFYKWszWB6C1RzIT11e0EGg9+SimwI/D/kbIdCfaKQv8AtliG9yufCd3+KegO1xgk2XQjaEEJ1nDyqX0Ak73MmWzsV8+bTErbZe+Wuw0T2B/Arj8fkmHlNHTUSh7GwWGv2k4uAQNRRcgjJdMhq0gZz/WBrYL7vL86vnBymfeDJkQ/bI+dX/gI0dx6pi4Sd2xvLhRz7tBbj64oCwpWnbD7M6oL8pkPtUrTnls4hdMVGa5F9ktvSXXNzwqZj2cCJHOpCz23D7m8Oj6zODSCbqh1u3wjKkyrC399/Fez7GTeyTL6Ln78yuqmzV0C6byGWDyWEMLd8o2N33zdUC7u7eGut5hwScyPHbRgcscDp/wHs=
