language: java

sudo: false

branches:
  except:
  - "/^feature.*$/"

jdk:
- oraclejdk8

env:
  global:
    secure: p/JtqN4m+6v4Amek5gCJTjZvHo2YPO/eIcsMooM/883DOwyP+XNgtJQKNmOn2HYb6oBO8LFMQccQzPimWBPKiec8s+f8IGqgmIuB6JRN0Db6KqfVQpy3nUFCCPVeOSzbNQ58OEVyc4oPSZDUbtOculmo+40n7KJIpOHA4kSjyeLZK7UtB8MIvhqC2WQX+Ulp7k+O/eJMmLYogDHagUkxSIdlAJPS3wWUyCV1FL7YnyTC6sFgh6afV47JbvtCWt7NanDz95gX0NArGFtuAOv49IrN8Svda7/Ba7KoGm9WtwMI0WJz/EdE9IqsrYSasrp6XvnVs8NNAw/foTqAORk0UTzAZ/X+1pueNpw7icRegaVJqVq07942dMZd4o4j5psnYb4qn1Pi7feG6NuOdvhta/QOan+QGjpBmWz1g6XEhBq7BmBzLiFbG+tLeRGvF/AL94Gy9nR9Jpv81dxMpjKqbk+OsQbIatCX1HcU2mJEtpN3ik5ZFoJ72y/q9uTI2RrDuCxDCV34V5rhdQzDUeAc7CoyU7M87sEi14uWuKwREEmA16FXY8YdRgfz5FAiVk+hXfdW/n5BAkaxLefochz1bBTECXvq0rsuRNriKetRTrXrBD8mwNES3eY1kAJbPz2VviEy7cYa7hK08KhJ8v2jFc10NyjBEIby5Xm0uO7ny78=

addons:
  coverity_scan:
    project:
      name: HBM/java-jet
      description: Build submitted via Travis CI
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew compileJava"
    branch_pattern: coverity_scan

